Update README.md
arguellesm/faux pull request #1
Opened 2021-09-20 22:02 UTC by arguellesm

**Objetivo 0**

- Añadida descripción del proyecto en `README.md`.

2021-09-21 10:39 UTC, JJ requested changes
Please take a look and revise accordingly.

2021-09-21 10:39 UTC, JJ commented on README.md
> +Faux is a Python-based API aimed to make it easier to detect fake news along the web.
No details on implementation, please. The scope of this PR is limited to an idea or problem to solve.

2021-09-21 10:39 UTC, JJ commented on README.md
> +### Why Faux
I see several possible issues with this. Most added value will probably arise from an external library, and even worse, from an external API and/or data source. It looks like an integration project, more than one that adds value by its own model or itself. Since you will have to revise this anyway, you have the chance to kind of come up with something that does not have those problems.

2021-09-21 10:55 UTC, JJ commented on README.md
> +### Why Faux
Possible outcome would be to specify, for instance, that the project is going to include a series of low-level metrics applied to the text that will give you a picture on how "fake" it is. You don't need to compute all metrics (at this moment), just that the value that you are going to provide with this is going to be this kind of measurements (as well as possibly processing raw text extracted from some news source).

2021-10-02 07:45 UTC, JJ commented
Can you change this with what we talked about in class, maybe?

2021-10-02 19:30 UTC, JJ requested changes
Still some way to go, just take a look at my suggestions.

2021-10-02 19:30 UTC, JJ commented on README.md
> +It analyzes texts and headlines to categorize them as fake news, clickbait articles or semingly-normal-things. On top of that, it provides information about how likely this prediction is based on its
typo: semingly

2021-10-02 19:30 UTC, JJ commented on README.md
> +
Please try and outline what's the business logic for the solution to this problem, and how it would leverage cloud for working.

2021-10-02 20:12 UTC, arguellesm commented on README.md
> +
Thanks for the feedback, although I don't know if I'm understanding the concept of business logic, wouldn't it be to use AI models (NLP and supervised machine learning) to develop an easy-access online tool to detect fake news and clickbait?

2021-10-02 20:14 UTC, arguellesm commented on README.md
> +It analyzes texts and headlines to categorize them as fake news, clickbait articles or semingly-normal-things. On top of that, it provides information about how likely this prediction is based on its
changed :thumbsup:

2021-10-03 06:59 UTC, JJ commented on README.md
> +
Please check out the mini-tutorial on the subject https://youtu.be/-ysmXDDEsAM and this objective description. Essentially, remember what we talked about in class: a series of non-trivial operations on the data that allows you to solve the problem. What you would need to do is
1. Clarify the kind of solution you propose for this (as we talked about in class, applying some simple heuristics to the text and the text metadata to perform classification ← this would be the business logic)
2. Clarify that this would leverage the cloud since the heuristics would be fine-tuned according to a continuously monitored system in the cloud (that would need, in objective 1, a specific user)

2021-10-05 20:51 UTC, arguellesm commented on README.md
> +
okay, i've added your suggestions!

2021-10-06 14:46 UTC, JJ approved these changes
:+1:

2021-10-06 18:02 UTC, merged