[IV-21-22] Objetivo 3
arguellesm/faux pull request #11
Opened 2021-11-22 13:12 UTC by arguellesm

I added **Poetry** for dependency management and **Invoke** as a task runner tool. The documentation, `iv.yaml` file and `README.md` of the project were modified accordingly to incorporate these changes.

2021-11-22 13:14 UTC, arguellesm commented
Ready to review :eyes: @jj

2021-11-22 13:16 UTC, JJ requested changes
You *really* need to justify technically the tools you've chosen, not just convey your decision.

2021-11-22 13:16 UTC, JJ commented on docs/dev_tools.md
> +[Invoke](https://www.pyinvoke.org/) is our task runner of choice.
You have to show what are the requirements for these, which other alternatives you have considered, and why this was the one you chose.

2021-11-22 13:17 UTC, JJ commented
Also, submit the PR.

2021-11-23 19:58 UTC, arguellesm commented on docs/dev_tools.md
> +[Invoke](https://www.pyinvoke.org/) is our task runner of choice.
done!

2021-11-23 19:59 UTC, arguellesm commented
Added alternatives in `dev_tools.md` and requirements in `README.md`. 

Ready to review @JJ

2021-11-28 11:05 UTC, JJ approved these changes
:+1: fair enough.

2021-11-28 11:05 UTC, JJ commented on docs/dev_tools.md
> +- [doit](https://pydoit.org/contents.html#)
You can't list stuff and *a posteriori* reasons to not choose them; all requirements need to be laid out *in advance*, as I commented in class. Please bear this in mind, because it will become increasingly important in the rest of the objectives.

2021-11-28 17:05 UTC, arguellesm commented on docs/dev_tools.md
> +- [doit](https://pydoit.org/contents.html#)
ok, I'll keep it in mind for the next ones, thanks! 👍🏼

2021-11-28 17:05 UTC, merged