[IV-21-22] Objetivo 4
arguellesm/faux pull request #14
Opened 2021-12-06 20:47 UTC by arguellesm

This PR:
- Starts implementing business logic via **blacklists** and a **Naive Bayes classifier algorithm**.
- Adds **tests** for the class `Article` managed with Pytest.

Checklist:

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?

* [x]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
   _Yes, articles have now a `predict()` method that returns the probability
of that article of being misleading or fake._

* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
   _[Milestone 0.2.0](https://github.com/arguellesm/faux/milestone/3)._

* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?

* [x]  ¿Se han documentado las elecciones de biblioteca de aserciones y de
   *framework* de test?

* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?

* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?

* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2021-12-06 20:59 UTC, arguellesm commented
@JJ ready! 👀

2021-12-07 17:12 UTC, JJ requested changes
Besides all that's been said, there's no business logic tested here.

2021-12-07 17:12 UTC, JJ commented on data/generate-df.py
> +	return file['text'], author
You should really use this in an OO way. You're simply returning an array. Clean code calls for using data structures for its purpose, and arrays were not made for this.

2021-12-07 17:12 UTC, JJ commented on docs/dev_tools.md
> +Invoke is our **task runner** of choice. It inherits a minimal yet
Again, don't tell me your choice. Show me your best effort to choose it, and the criteria you have followed.

2021-12-07 17:12 UTC, JJ commented on docs/dev_tools.md
>    _doit_ has quite a similar approach to Invoke and uses Python as
... which is why it's used in Python.

2021-12-07 17:12 UTC, JJ commented on docs/dev_tools.md
> + Pytest is both our **test framework** and **assertion library** of
No, it's not. It barely has any assertions.

2021-12-07 17:12 UTC, JJ commented on docs/dev_tools.md
> +for `python + [term]` and `python + [term] + stackoverflow`. These were
??? stackoverflow why?

2021-12-07 17:12 UTC, JJ commented on docs/dev_tools.md
> +  - [Unittest](https://docs.python.org/3/library/unittest.html)
Where have I seen this before? Ah, above. Where it does not belong. You can call it a test framework, but it's not by any means in the same class as pytest.

2021-12-07 17:12 UTC, JJ commented on test/article_test.py
> +    assert Article(headline='A simple headline')
This assertion does not belong to pytest. That means that you're not using pytest as an assertion library as you claim.

2021-12-07 20:37 UTC, arguellesm commented on data/generate-df.py
> +	return file['text'], author
I've modified it to make it cleaner, although this script is not part of the application it self, it's just a tool in case someone wants to replicate how the dataframe was created, as the version from FakeHealth has a different format.

2021-12-07 20:39 UTC, arguellesm commented on docs/dev_tools.md
> +Invoke is our **task runner** of choice. It inherits a minimal yet
The reason for choosing Invoke was that its community seems quite bigger. I find this useful for understanding and troubleshooting issues I might have in the future.

2021-12-07 20:41 UTC, arguellesm commented on docs/dev_tools.md
> +  - [Unittest](https://docs.python.org/3/library/unittest.html)
I've modified this to include Unittest and the `assert` statement as the assertion library/tools 👍🏼

2021-12-07 20:47 UTC, arguellesm commented
> Besides all that's been said, there's no business logic tested here.

I don't understand why. Business logic here includes predicting whether an article might be fake or not and to what extent, and I understand that's tested with:

```python
test_predict_returns_three_values()
test_predict_probability_between_0_and_1()
test_author_score_is_0()
test_source_score_is_0()
```

I guess I'm missing something but I don't know what (?)

Other than that, ready for review @JJ

2021-12-08 12:42 UTC, JJ requested changes
Besides the issues about justification, you should test your own logic, not something contained in a pickled model. If you need a simpler model for a MVP, create that model. But it's always about testing *your* code for *your* business logic.

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> +Invoke is our **task runner** of choice. It inherits a minimal yet
You should state your criteria before the tool you've chosen. If you don't, it looks like you're simply justifying what you had decided in advance. Also, not this objective, but the previous one. I should have told you so there.

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> + Pytest is both our **test framework** of
both what?

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> + - Well documented, preferably with a wide community behind it.
Again, criteria should be announced in advance, and should not be subjective, like "well documented". Are the others badly documented?

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> + - Already included in Python.
It's *not* included in Python.

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> +  - [Unittest](https://docs.python.org/3/library/unittest.html)
This is not a test runner. Pytest includes a test runner. I explained in class what's the concept of test runner, including the fact that it's able to parse TAP output.

2021-12-08 12:42 UTC, JJ commented on docs/dev_tools.md
> +To allow simplicity when needed, we'll be also using the `assert`
How do you test exceptions then? Also, why don't you include possible exceptions in your code?

2021-12-08 12:42 UTC, JJ commented on pyproject.toml
> +scikit-learn = "^1.0.1"
Is this used?

2021-12-08 12:42 UTC, JJ commented on pyproject.toml
> +pytest = "^6.2.5"
Is this a production or a dev dependency?

2021-12-08 12:42 UTC, JJ commented on src/article.py
> +        model = pickle.load(file)
This is not your own logic, it's a model you've picked up from elsewhere. You're not really testing your logic, but some other logic. This objective is about whitelist testing, and about testing your own business logic.

2021-12-08 12:42 UTC, JJ commented on src/article.py
> +        file = open(os.path.dirname(__file__)+'/../model/mnb.pkl', 'rb')
Not testing for errors, and also including a literal when it should be a constant.

2021-12-09 20:40 UTC, arguellesm commented on docs/dev_tools.md
> +Invoke is our **task runner** of choice. It inherits a minimal yet
I've changed the structure of `dev_tools.md` in https://github.com/arguellesm/faux/pull/14/commits/7fa7ae2b94212e4514d805a78c706c74b4463edd to always list criteria first, then the alternatives I found and finally the option I ended up choosing.

The ones from the last objective are obviously done retroactively, but I'll keep it in mind in the future.

2021-12-09 20:41 UTC, arguellesm commented on docs/dev_tools.md
> + Pytest is both our **test framework** of
fixed 👍🏼

2021-12-09 20:41 UTC, arguellesm commented on docs/dev_tools.md
> + - Well documented, preferably with a wide community behind it.
I removed this criterion from the list 👍🏼

2021-12-09 20:44 UTC, arguellesm commented on docs/dev_tools.md
> + - Already included in Python.
When listing criteria I don't expect the final tool to meet all of them. They're meant as a guide to give some alternatives preference over others.

2021-12-09 20:48 UTC, arguellesm commented on pyproject.toml
> +pytest = "^6.2.5"
I believe they're regular dependencies as they are always needed for the product to function properly.

2021-12-09 20:56 UTC, arguellesm commented on src/article.py
> +        model = pickle.load(file)
I did the model myself as described in [model.ipynb](https://github.com/arguellesm/faux/blob/7fa7ae2b94212e4514d805a78c706c74b4463edd/model/model.ipynb) from  https://github.com/arguellesm/faux/pull/14/commits/131f57aac56d2e1b1bfbdbc55d39f625370d9df6. At the end of that notebook, the model is pickled to use it in the project.

2021-12-09 20:56 UTC, arguellesm commented on src/article.py
> +        file = open(os.path.dirname(__file__)+'/../model/mnb.pkl', 'rb')
changed 👍🏼

2021-12-09 21:13 UTC, arguellesm commented
@JJ ready for review

2021-12-10 06:18 UTC, JJ requested changes
Still some problems.
1. Try to establish some real criteria for choosing libraries. We talked about that yesterday in class.
2. Try to open up a bit your horizon of possible tools.
3. If you don't really test your own business logic, but an external model, you should at least develop exceptions and test them.
4. The "predict" function does several different things. It should have separated functions (separation of concerns) that should be tested independently.
5. Please try and understand the difference between production and development dependencies and use them accordingly.

2021-12-10 06:18 UTC, JJ commented on docs/dev_tools.md
> +### Dependency management
No one is requesting you to select a tool for dependency management. Most languages have just one, so it's not really worth the while.

2021-12-10 06:18 UTC, JJ commented on docs/dev_tools.md
> +- Common within the Python community
None of these criteria are really measurable or have any relation to your own project.

2021-12-10 06:18 UTC, JJ commented on docs/dev_tools.md
> +Even though Unittest is already included in Python, we opted
Not comparable, not by a long shot. pytest is a test runner with a few assertions (mainly to complement assert), unittest is a testing framework without a test runner. Also, there are other tests runners and assertion libraries.

2021-12-10 06:18 UTC, JJ commented on pyproject.toml
> +scikit-learn = "^1.0.1"
Not clear why you need to pickle the model.

2021-12-10 06:18 UTC, JJ commented on pyproject.toml
> +pytest = "^6.2.5"
No, they're not. Testing is not a production operation, it's a dev operation.

2021-12-10 06:18 UTC, JJ commented on src/article.py
> +class CantLoadContentModelError(FileNotFoundError):
Not developing or testing this. It's essential that you test exceptions.

2022-02-04 23:38 UTC, arguellesm commented on docs/dev_tools.md
> +- Common within the Python community
I changed this and tried to add ways of measuring them. They still don't have any particular relation to my project, but that's because I don't think the project needs anything too specific from the test runner or assertion library.

2022-02-04 23:38 UTC, arguellesm commented on src/article.py
> +class CantLoadContentModelError(FileNotFoundError):
Done.

2022-02-04 23:49 UTC, arguellesm commented
Just a few comments. I believe I improved the biggest issues pointed out before:

1. Criteria are better know, with objective and measurable attributes.
2. I broaden my range of possible tools searching for different assertion libraries that I didn't consider before.
3. Exceptions are being tested now. There is one exception (no pun intended) to this: `ArticleDependencyError` will raise when a dependency is missing. This can't happen with the current Poetry setup, which is also used to run tests.
4. The `predict` function is now split up into three different ones, that are also tested on their own: `rate_author`, `rate_source` and `rate_content`.
5. Dev dependencies now include Invoke, Pytest and Pytruth.

2022-02-04 23:54 UTC, JJ commented
⛹ Revisores → @Mapachana @Paszser @Parka015

2022-02-08 13:20 UTC, JJ commented on data/generate-df.py
> +	return file['text'], author
Best practices should be applied all across the project, not only in modules.

2022-02-08 13:23 UTC, JJ commented on docs/dev_tools.md
> + - Already included in Python.
There's no test runner included in Python. No use to put up criteria that's going to be met by no tool.

2022-02-08 13:26 UTC, JJ commented on src/article.py
> +        model = pickle.load(file)
You need to do it *as part of the project*, with business logic that's part of the current minimally viable product. That issue is related to #12, which is not related to any HU whatsoever. If it's not advancing an US, it's not adding value to the customer.
Remember, this objective is not about testing. It's about advancing your project to a minimally viable product that includes business logic and can be, from now on, tested with the also included infrastructure.

2022-02-08 13:28 UTC, JJ commented on docs/dev_tools.md
> +- Common within the Python community
Projects *always* need something specific, if only because they have been created at a specific point in time and should use the best practices available at that specific time.

2022-02-08 13:30 UTC, JJ commented on docs/dev_tools.md
> + Pytest is both our **test framework** and **assertion library** of
> Just a few comments. I believe I improved the biggest issues pointed out before:
> 
>     1. Criteria are better know, with objective and measurable attributes.
> 
>     2. I broaden my range of possible tools searching for different assertion libraries that I didn't consider before.
> 
>     3. Exceptions are being tested now. There is one exception (no pun intended) to this: `ArticleDependencyError` will raise when a dependency is missing. This can't happen with the current Poetry setup, which is also used to run tests.
> 
>     4. The `predict` function is now split up into three different ones, that are also tested on their own: `rate_author`, `rate_source` and `rate_content`.
> 
>     5. Dev dependencies now include Invoke, Pytest and Pytruth.

Not a single one of the new commits refer to any issue. If they are addressing the PR comments, they should refer to them.

2022-02-08 13:55 UTC, JJ approved these changes
I wouldn't probably pass this if you had the chance to send it again. But you don't, so it's either hit or miss. Main positive point is to have tried and be original with the assertion library, and try to test the business logic (although, again, you need to use only your own code). There are many negative points that have been pointed out, and that will probably jeopardize the fulfillment of the rest of the objectives if you don't address them.

2022-02-08 13:55 UTC, JJ commented on data/README.md
> +currently intereted in. We've extracted the following fields of interest and
typo

2022-02-08 13:55 UTC, JJ commented on data/README.md
> +
At this point, you should have probably just modeled what's in that data and/or faked it. If you decide to process it, you should have created an issue for it, included in a milestone, and associated it to an US

2022-02-08 13:55 UTC, JJ commented on data/generate-df.py
> +import pandas as pd
Not a single line of this file is associated with an issue. Working with issues was essential since objective 2. Again, you don't need real data to test, test data can simply be fake data. If it's the structure you're looking for, you should have created an issue to model that.

2022-02-08 13:55 UTC, JJ commented on data/generate-df.py
> +		author = file['authors']
This is the consequence of not creating issues for modeling the problem domain. You're putting author and authors in the same output variable, when quite obviously one of them is singular and the other plural. You're also extracting information without any reference of what or how it's going to be used in your business logic. At this point in the project, it's essential that you understand, model, solve what's going or not going to be included as classes in your project.

2022-02-08 13:55 UTC, JJ commented on data/generate-df.py
> +	headline 	= []
All these variables are in singular, while they are initialized with an array. Clean code calls for "semantic" identifiers, that really point to what they hold or contain.

2022-02-08 13:55 UTC, JJ commented on data/generate-df.py
> +		author.append(get_author(path))
[`append`](https://towardsdatascience.com/append-in-python-41c37453400) appends a single item; if it's the result of the original "authors" field you either are going to add an array as a single item, or are going to add a (possibly comma) separated list of authors as a single one. Not clear what's the case here, but again this is a reason why you need to *always* add to the repo according to HUs/issues.

2022-02-08 13:55 UTC, JJ commented on docs/dev_tools.md
> +### Dependency management
Again, not addressed. You should have merged to main all this part and eliminated it from here.

2022-02-08 13:55 UTC, JJ commented on docs/dev_tools.md
> +### Test framework
We ask for two things (please check out the revised objective description):
* a *test runner*
* an *assertion library*

Talking about testing frameworks is misleading, because it can include everything, from mocking  libraries to runner-assertion-coverage combos.

2022-02-08 13:55 UTC, JJ commented on docs/dev_tools.md
> +
Again, you shouldn't. You should have tried and understand first, as we told in class, what's a test runner, and what are assertion libraries.

2022-02-08 13:55 UTC, JJ commented on docs/dev_tools.md
> +Even though Unittest is already included in Python, we opted
Not addressed.

2022-02-08 13:55 UTC, JJ commented on src/article.py
> +from src import globals, blacklists
Best practices dictate that the module should be in a directory with the name of the project. It should never be "src"

2022-02-08 13:55 UTC, JJ commented on src/article.py
>          if(globals.AUTHOR_MAX_LENGHT > len(author)):
typo. Also, don't understand why tests are not all here.

2022-02-08 13:55 UTC, JJ commented on test/article_test.py
> +    assert Article(headline='A simple headline')
Still don't belong to that. if you use truth, you should also use it here.

2022-02-08 13:55 UTC, JJ commented on tasks.py
> +    c.run('python -m pytest test')
Why not simply pytest?

2022-02-09 01:37 UTC, arguellesm commented on data/README.md
> +
Addressed below

2022-02-09 01:37 UTC, arguellesm commented on data/generate-df.py
> +import pandas as pd
Addressed below

2022-02-09 01:37 UTC, arguellesm commented on data/generate-df.py
> +		author = file['authors']
Addressed below

2022-02-09 01:37 UTC, arguellesm commented on data/generate-df.py
> +	headline 	= []
Addressed below

2022-02-09 01:40 UTC, arguellesm commented on data/generate-df.py
> +		author.append(get_author(path))
It adds an array of authors. I've changed the variable name to `authors` to make it more descriptive.

2022-02-09 01:40 UTC, arguellesm commented on docs/dev_tools.md
> +### Test framework
Changed 👍🏼

2022-02-09 01:40 UTC, arguellesm commented on src/article.py
> +from src import globals, blacklists
Changed name to `faux` 👍🏼

2022-02-09 01:42 UTC, arguellesm commented on src/article.py
>          if(globals.AUTHOR_MAX_LENGHT > len(author)):
All tests are in the `/test` directory. I didn't fix the typo because I couldn't find it.

2022-02-09 01:45 UTC, arguellesm commented on tasks.py
> +    c.run('python -m pytest test')
I left it like that because it added the current path to `sys.path`, but I don't really use that. Changed to plain `pytest` 👍🏼

2022-02-09 01:55 UTC, arguellesm commented
Addressing the issues in `generate_df.py`:

- This file shouldn't have been included here in the first place. It's a script to (sort of) turn a JSON file into a CSV dataframe that 
it's not a requirement for the project. However, I opted for including it for documentation and replication purposes, so that anyone could see where the `.csv` file came from. I now see several problems with this:
  - There is no need to have a 'proper dataset' at this stage and   I should have used that data as dummy or fake data as you suggest.
  - By doing so, there will be no point in documenting that, not to mention providing the means to replicate it.
  - The script was thought of as a tool to generate something else and be discarded later, not as an integral part of the project, and for that reason it shouldn't have been added to the repository.
  
- On top of that, there are many issues with the `generate_df.py` script and the original JSON dataset. It was difficult to extract meaningful data because some categories would have multiple names (like 'author' and 'authors'), some keys wouldn't be present for all instances, and many values were blank. This and the fact that the script wasn't initially meant to be shared led to a messy and not very thoughtful script. It was also a mistake to rush and force having "real" data, as this could have been easily avoided with fake data, as commented before.

- I've modified a few things from `generate_df.py` to answer some of your comments, although I believe the best option would be to delete the file and consider the model was trained on fake data. Even further, there should be no data to train the model on as the model should be replaced by another implementation of the business logic that didn't require external libraries.

**tl;dr** I've made some changes to `generate_df.py` to address your comments. Regardless, I believe the best alternative would be to consider the model was based on fake/dummy data and delete `generate_df.py`.

2022-03-03 11:00 UTC, merged